services:

  # ==========================================================
  # Application
  # ==========================================================
  application:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    image: ai-resume-application

    env_file:
      - ../src/.env

    environment:
      VECTOR_DB_PATH: "/app/src/assets/vectordb"

    ports:
      - "8000:8000"

    volumes:
      - ../src/assets:/app/src/assets