"""Add ATS Pipeline Models

Revision ID: 213df9a0e310
Revises: aa68720ebb06
Create Date: 2026-10-06 21:46:01.167004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '213df9a0e310'
down_revision: Union[str, Sequence[str], None] = 'aa68720ebb06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('jd_id', sa.String(), nullable=False),
    sa.Column('stage', sa.Enum('APPLIED', 'CONTACTED', 'CONSIDERED', 'INTERVIEWING', 'OFFER_SENT', 'HIRED', 'REJECTED', 'CANCELLED', name='pipelinestage'), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company_profiles.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ),
    sa.ForeignKeyConstraint(['jd_id'], ['job_descriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('candidate_requests')
    op.add_column('job_descriptions', sa.Column('is_public', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_descriptions', 'is_public')
    op.create_table('candidate_requests',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('jd_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', name='requeststatus'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company_profiles.id'], name=op.f('candidate_requests_company_id_fkey')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], name=op.f('candidate_requests_customer_id_fkey')),
    sa.ForeignKeyConstraint(['jd_id'], ['job_descriptions.id'], name=op.f('candidate_requests_jd_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('candidate_requests_pkey'))
    )
    op.drop_table('job_applications')
    # ### end Alembic commands ###
