"""Multiple CVs and JD enrichments

Revision ID: f9a69b3496ce
Revises: 213df9a0e310
Create Date: 2026-10-07 15:56:09.494315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9a69b3496ce'
down_revision: Union[str, Sequence[str], None] = '213df9a0e310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('vector_id', sa.String(), nullable=False),
    sa.Column('is_primary', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('customer_profiles', 'cv_vector_id')
    op.drop_column('customer_profiles', 'cv_file_path')
    op.add_column('job_applications', sa.Column('document_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'job_applications', 'candidate_documents', ['document_id'], ['id'])
    op.add_column('job_descriptions', sa.Column('location', sa.String(), nullable=True))
    op.add_column('job_descriptions', sa.Column('job_type_id', sa.String(), nullable=True))
    op.add_column('job_descriptions', sa.Column('job_function_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'job_descriptions', 'job_types', ['job_type_id'], ['id'])
    op.create_foreign_key(None, 'job_descriptions', 'job_functions', ['job_function_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'job_descriptions', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'job_descriptions', type_='foreignkey')
    op.drop_column('job_descriptions', 'job_function_id')
    op.drop_column('job_descriptions', 'job_type_id')
    op.drop_column('job_descriptions', 'location')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'job_applications', type_='foreignkey')
    op.drop_column('job_applications', 'document_id')
    op.add_column('customer_profiles', sa.Column('cv_file_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customer_profiles', sa.Column('cv_vector_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('candidate_documents')
    # ### end Alembic commands ###
