
DefaultTaxonomy = {
    "software_engineering": [
        "python", "java", "javascript", "typescript", "c++", "c#", "go", "rust",
        "ruby", "php", "swift", "kotlin", "scala", "r", "perl", "lua", "dart",
        "html", "css", "sass", "less",
        "react", "angular", "vue.js", "svelte", "next.js", "nuxt.js",
        "node.js", "express.js", "fastapi", "django", "flask", "spring boot",
        "ruby on rails", "laravel", "asp.net", "gin",
        "rest api", "graphql", "grpc", "websockets", "microservices",
        "sql", "postgresql", "mysql", "mongodb", "redis", "elasticsearch",
        "sqlite", "oracle", "cassandra", "dynamodb", "neo4j", "couchdb",
        "git", "github", "gitlab", "bitbucket",
        "unit testing", "integration testing", "test driven development",
        "jest", "pytest", "junit", "selenium", "cypress",
        "webpack", "vite", "babel", "npm", "yarn", "pip",
        "linux", "bash", "shell scripting", "powershell",
        "agile", "scrum", "kanban", "jira", "confluence",
        "visual studio code", "intellij", "vim"
    ],
    "data_science_and_analytics": [
        "machine learning", "deep learning", "natural language processing", "nlp",
        "computer vision", "reinforcement learning", "neural networks",
        "tensorflow", "pytorch", "keras", "scikit-learn", "xgboost", "lightgbm",
        "pandas", "numpy", "scipy", "matplotlib", "seaborn", "plotly",
        "jupyter", "google colab",
        "statistics", "probability", "linear regression", "logistic regression",
        "decision trees", "random forest", "support vector machines",
        "clustering", "dimensionality reduction", "pca",
        "feature engineering", "model evaluation", "cross validation",
        "a/b testing", "hypothesis testing", "bayesian statistics",
        "time series analysis", "forecasting",
        "data visualization", "tableau", "power bi", "looker", "metabase",
        "data warehousing", "etl", "data pipeline", "data modeling",
        "sql", "spark", "hadoop", "hive", "presto", "dbt",
        "snowflake", "redshift", "bigquery", "databricks",
        "spacy", "hugging face", "transformers", "bert", "gpt",
        "langchain", "llm", "prompt engineering", "rag",
        "chromadb", "pinecone", "weaviate", "faiss",
        "mlflow", "wandb", "dvc", "model deployment",
        "data cleaning", "data wrangling", "exploratory data analysis",
        "excel", "google sheets", "sas", "spss", "stata"
    ],
    "devops_and_cloud": [
        "docker", "kubernetes", "container orchestration",
        "aws", "amazon web services", "ec2", "s3", "lambda", "ecs", "eks",
        "rds", "cloudformation", "sagemaker",
        "gcp", "google cloud platform", "compute engine", "cloud functions",
        "cloud run", "gke", "cloud storage",
        "azure", "azure devops", "azure functions", "aks",
        "terraform", "ansible", "puppet", "chef", "pulumi",
        "ci/cd", "jenkins", "github actions", "gitlab ci", "circleci",
        "travis ci", "argo cd", "tekton",
        "nginx", "apache", "load balancing", "reverse proxy",
        "monitoring", "prometheus", "grafana", "datadog", "new relic",
        "splunk", "elk stack", "logstash", "kibana",
        "infrastructure as code", "configuration management",
        "networking", "dns", "tcp/ip", "http", "ssl/tls", "vpn",
        "linux administration", "windows server",
        "service mesh", "istio", "envoy",
        "helm", "kustomize",
        "site reliability engineering", "sre", "incident management"
    ],
    "cybersecurity": [
        "penetration testing", "vulnerability assessment", "ethical hacking",
        "network security", "application security", "cloud security",
        "siem", "splunk", "qradar", "sentinel",
        "firewall", "ids", "ips", "intrusion detection",
        "encryption", "cryptography", "pki", "ssl/tls",
        "identity management", "access control", "oauth", "saml", "sso",
        "soc", "security operations", "threat intelligence",
        "malware analysis", "reverse engineering", "forensics",
        "compliance", "iso 27001", "soc 2", "pci dss", "gdpr", "hipaa",
        "nist", "cis benchmarks",
        "owasp", "secure coding", "code review",
        "endpoint security", "edr", "xdr",
        "risk assessment", "security audit",
        "incident response", "disaster recovery", "business continuity",
        "devsecops", "container security", "zero trust"
    ],
    "design_and_ux": [
        "figma", "sketch", "adobe xd", "invision",
        "adobe photoshop", "adobe illustrator", "adobe indesign",
        "adobe after effects", "adobe premiere pro",
        "canva", "coreldraw",
        "ui design", "ux design", "user interface", "user experience",
        "wireframing", "prototyping", "mockup",
        "user research", "usability testing", "a/b testing",
        "information architecture", "interaction design",
        "responsive design", "mobile design", "web design",
        "design systems", "style guide", "brand guidelines",
        "typography", "color theory", "layout design",
        "accessibility", "wcag", "inclusive design",
        "motion design", "animation",
        "3d modeling", "blender", "cinema 4d",
        "design thinking", "human centered design",
        "storyboarding", "journey mapping", "persona development"
    ],
    "marketing_and_growth": [
        "seo", "search engine optimization", "sem", "search engine marketing",
        "google ads", "facebook ads", "instagram ads", "linkedin ads",
        "ppc", "pay per click", "display advertising", "programmatic advertising",
        "google analytics", "google tag manager", "google search console",
        "social media marketing", "content marketing", "email marketing",
        "copywriting", "content writing", "blog writing", "technical writing",
        "marketing automation", "hubspot", "marketo", "mailchimp", "salesforce marketing cloud",
        "crm", "salesforce", "zoho", "pipedrive",
        "conversion rate optimization", "landing page optimization",
        "brand management", "brand strategy", "market research",
        "competitive analysis", "swot analysis",
        "public relations", "press releases", "media relations",
        "influencer marketing", "affiliate marketing",
        "video marketing", "youtube", "tiktok marketing",
        "analytics", "data driven marketing", "attribution modeling",
        "growth hacking", "product led growth", "customer acquisition",
        "retention marketing", "customer lifetime value",
        "marketing strategy", "go to market strategy",
        "adobe analytics", "mixpanel", "amplitude", "segment"
    ],
    "finance_and_accounting": [
        "financial modeling", "financial analysis", "financial reporting",
        "budgeting", "forecasting", "variance analysis",
        "accounting", "bookkeeping", "general ledger",
        "accounts payable", "accounts receivable",
        "gaap", "ifrs", "financial statements",
        "balance sheet", "income statement", "cash flow statement",
        "tax preparation", "tax planning", "tax compliance",
        "auditing", "internal audit", "external audit",
        "risk management", "credit analysis", "credit risk",
        "investment analysis", "portfolio management", "asset management",
        "valuation", "dcf", "comparable analysis", "mergers and acquisitions",
        "private equity", "venture capital", "investment banking",
        "corporate finance", "treasury", "working capital management",
        "erp", "sap", "oracle financials", "netsuite", "quickbooks",
        "excel", "financial modeling excel", "vba", "power bi",
        "bloomberg terminal", "capital iq", "factset",
        "regulatory compliance", "sox compliance", "aml", "kyc",
        "insurance", "underwriting", "actuarial",
        "payroll", "benefits administration",
        "cost accounting", "management accounting",
        "cryptocurrency", "blockchain", "defi"
    ],
    "healthcare": [
        "electronic health records", "ehr", "emr",
        "epic", "cerner", "meditech", "allscripts",
        "medical coding", "icd-10", "cpt", "hcpcs",
        "medical billing", "revenue cycle management",
        "hipaa", "hipaa compliance", "phi", "patient privacy",
        "clinical research", "clinical trials", "gcp", "fda regulations",
        "patient care", "patient assessment", "care coordination",
        "nursing", "registered nurse", "nurse practitioner",
        "pharmacy", "pharmacology", "medication management",
        "radiology", "medical imaging", "dicom",
        "laboratory", "lab testing", "pathology",
        "telemedicine", "telehealth", "remote patient monitoring",
        "health informatics", "health data analytics",
        "medical terminology", "anatomy", "physiology",
        "infection control", "quality improvement",
        "public health", "epidemiology", "biostatistics",
        "mental health", "behavioral health", "counseling",
        "physical therapy", "occupational therapy", "rehabilitation",
        "medical devices", "biomedical engineering",
        "healthcare management", "hospital administration"
    ],
    "human_resources": [
        "recruiting", "talent acquisition", "sourcing",
        "applicant tracking system", "ats", "greenhouse", "lever", "workday",
        "interviewing", "candidate screening", "reference checks",
        "onboarding", "employee onboarding", "orientation",
        "hris", "human resource information system", "bamboohr", "adp", "paychex",
        "employee relations", "conflict resolution", "mediation",
        "performance management", "performance reviews", "goal setting",
        "compensation", "benefits", "total rewards",
        "payroll processing", "payroll administration",
        "learning and development", "training", "coaching", "mentoring",
        "organizational development", "change management",
        "succession planning", "workforce planning", "talent management",
        "diversity and inclusion", "dei", "equity",
        "employment law", "labor law", "compliance",
        "employee engagement", "culture building", "retention",
        "hr analytics", "people analytics", "workforce analytics",
        "job analysis", "job descriptions", "competency modeling"
    ],
    "project_management": [
        "project planning", "project scheduling", "project budgeting",
        "agile", "scrum", "kanban", "lean", "waterfall",
        "scrum master", "product owner", "sprint planning",
        "jira", "confluence", "trello", "asana", "monday.com",
        "microsoft project", "smartsheet", "basecamp",
        "risk management", "risk assessment", "risk mitigation",
        "stakeholder management", "stakeholder communication",
        "resource management", "resource allocation",
        "scope management", "requirements gathering",
        "pmp", "prince2", "capm", "safe",
        "program management", "portfolio management",
        "change management", "process improvement",
        "six sigma", "lean six sigma", "kaizen",
        "gantt chart", "work breakdown structure", "critical path",
        "earned value management", "kpi", "metrics",
        "vendor management", "contract management", "procurement",
        "quality management", "quality assurance",
        "business analysis", "requirements analysis", "user stories"
    ],
    "legal": [
        "contract management", "contract drafting", "contract review",
        "legal research", "case law", "statutory law",
        "litigation", "dispute resolution", "arbitration", "mediation",
        "corporate law", "business law", "commercial law",
        "intellectual property", "patent", "trademark", "copyright",
        "regulatory compliance", "regulatory affairs",
        "data privacy", "gdpr", "ccpa", "privacy law",
        "employment law", "labor law", "workplace compliance",
        "real estate law", "property law",
        "mergers and acquisitions", "due diligence",
        "legal writing", "legal drafting", "brief writing",
        "ediscovery", "document review", "legal hold",
        "legal technology", "legal ops", "contract lifecycle management",
        "risk management", "legal risk assessment",
        "corporate governance", "board management",
        "tax law", "estate planning", "trusts",
        "immigration law", "visa processing",
        "environmental law", "health law",
        "westlaw", "lexisnexis", "legal databases"
    ],
    "sales": [
        "sales strategy", "sales planning", "territory management",
        "lead generation", "prospecting", "cold calling", "cold emailing",
        "crm", "salesforce", "hubspot crm", "zoho crm", "pipedrive",
        "sales pipeline", "pipeline management", "deal closing",
        "negotiation", "contract negotiation", "pricing strategy",
        "account management", "key account management", "client relations",
        "business development", "partnership development",
        "solution selling", "consultative selling", "value selling",
        "saas sales", "enterprise sales", "inside sales", "field sales",
        "sales forecasting", "quota management", "revenue forecasting",
        "presentation skills", "demo skills", "product demonstration",
        "objection handling", "closing techniques",
        "customer success", "customer retention", "upselling", "cross selling",
        "channel sales", "partner sales", "reseller management",
        "sales enablement", "sales training", "sales coaching",
        "market analysis", "competitive intelligence",
        "linkedin sales navigator", "outreach", "salesloft"
    ],
    "mechanical_and_electrical_engineering": [
        "autocad", "solidworks", "catia", "creo", "inventor",
        "3d modeling", "3d printing", "additive manufacturing",
        "finite element analysis", "fea", "ansys", "abaqus",
        "computational fluid dynamics", "cfd",
        "cad", "cam", "cae",
        "manufacturing", "cnc machining", "injection molding",
        "quality control", "six sigma", "lean manufacturing",
        "gd&t", "geometric dimensioning and tolerancing",
        "materials science", "metallurgy", "composites",
        "thermodynamics", "heat transfer", "fluid mechanics",
        "mechanical design", "mechanism design", "machine design",
        "pcb design", "altium", "kicad", "eagle",
        "circuit design", "analog design", "digital design",
        "embedded systems", "microcontrollers", "arduino", "raspberry pi",
        "plc", "scada", "industrial automation",
        "control systems", "pid control", "feedback systems",
        "signal processing", "dsp",
        "power systems", "power electronics", "motor control",
        "robotics", "ros", "autonomous systems",
        "matlab", "simulink", "labview",
        "project management", "technical documentation",
        "iso 9001", "as9100", "iatf 16949"
    ]
}